language: python
sudo: required
python:
  - "2.7"
cache:
  directories:
    - $HOME/.cache/pip
branches:
  only:
    - master
    - develop

# commands to install dependencies
# before_install:
#     - sudo apt-get -qq update
#     - sudo apt-get -y install python-libsbml

# apt add-on
addons:
  apt:
    packages:
    - python-libsbml
    - python-libsedml

install:
    - pip install Cython
    - pip install -r requirements.txt

# command to run tests
script: nosetests