language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"

branches:
  only:
    - master
    - develop

install:
  pip install -r requirements.txt

script:
  pytest

after_success:
   pip install codecov
   codecov
