language: python
python:
  - "2.7"

branches:
  only:
    - master
    - develop

# command to install dependencies
install:
    - pip install Cython
    - pip install -r requirements.txt

# command to run tests
script: nosetests