language: python
sudo: true
python:
  - "2.7"

branches:
  only:
    - master
    - develop

# commands to install dependencies
install:
    - sudo apt-get -y install python-libsbml
    - sudo apt-get -y install python-libsedml
    - pip install Cython
    - pip install -r requirements.txt

# command to run tests
script: nosetests