language: python
python: '3.5'
sudo: false
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all

branches:
  only:
    - master
    - develop

install:
  pip install -r requirements.txt

script:
  pytest

after_success:
   pip install codecov
   codecov
