language: python
sudo: required
python:
  - "2.7"
cache:
  directories:
    - $HOME/.cache/pip
branches:
  only:
    - master
    - develop

# commands to install dependencies
before_install:
  - (git clone https://github.com/matthiaskoenig/linux-setup.git && cd linux-setup && git checkout v0.1)
  - ls
  - sudo sh linux-setup/simulation.sh

install:
    - pip install Cython
    - pip install -r requirements.txt

# command to run tests
script: nosetests